### ISSUE TITLE
Export Network to Image file

### ISSUE THREAD

**Issue by nrf1** [CDCgov/MicrobeTrace-Archive#10]
It would be very useful to be able to export an image of the network, for example as a PDF or JPEG.

**Comment by ells** [comment]
In addition, the ability to export the computed edge list is critical.

**Comment by AABoyles** [comment]
Agree, @ells: going to spawn an new issue for that, since it's a technically distinct problem.

**Comment by AABoyles** [comment]
See #21

**Comment by AABoyles** [comment]
Resolved by ee860e5578e81d9a773f5f02bdc3fc07070184d6

**Comment by AABoyles** [comment]
Improved by 1e2afb7ddfeed837c94ae515005d86e827b9e01b, added JPEG output (plus non-functional commented code stub for BMP)
