### ISSUE TITLE
Typos/name changes

### ISSUE THREAD

**Issue by ikb6** [CDCgov/MicrobeTrace-Archive#112]
#Under Phylogeny, distance matrix configuration, the text when you hover over "Sort deepest clades to **bottom** has a typo"
Github help text for Histogram view has WinHIVTrace.

**Comment by AABoyles** [comment]
The Histogram view help text can be edited [here](https://github.com/CDCgov/MicrobeTRACE/wiki/Histogram).

**Comment by AABoyles** [comment]
Resolved by 535d00167c01a3e2be6aaad0a019fe26c00fd139 and 33add8a52dcf55afd529b7b3d7d8057dbabca7b9
