### ISSUE TITLE
Github text says Distance matrix

### ISSUE THREAD

**Issue by ikb6** [CDCgov/MicrobeTrace-Archive#115]
In the pulldown menu this is now called Heatmap. Github still has it as distance matrix. Took me a while to find it.

**Comment by AABoyles** [comment]
Good catch. [It's fixed](https://github.com/CDCgov/MicrobeTRACE/wiki).

Just FYI, you can edit these typos by going to the [Wiki](https://github.com/CDCgov/MicrobeTRACE/wiki) and pressing the [Edit button](https://github.com/CDCgov/MicrobeTRACE/wiki/Home/_edit).

**Comment by ikb6** [comment]
Good to know- will do it myself if I find any more!

________________________________
