### ISSUE TITLE
File menu still has "Export HIVTrace file" as an option

### ISSUE THREAD

**Issue by ikb6** [CDCgov/MicrobeTrace-Archive#116]

**Comment by AABoyles** [comment]
I left that for...aspirational reasons? I still mean to implement a full HIVTrace export capability (#71), but it's a non-trivial task. I'm going to hide the widget for now.

**Comment by AABoyles** [comment]
Resolved by 0cb97bd158d1139caf937a4a5bb6be381dc91fe1
