### ISSUE TITLE
Include unconnected nodes in an edge list

### ISSUE THREAD

**Issue by nrf1** [CDCgov/MicrobeTrace-Archive#12]
When using the option to upload an edge list, there does not seem to be a way to include unlinked nodes.

**Comment by AABoyles** [comment]
I don't quite understand the issue here. How would you even specify a node with no edges in a edge list?

**Comment by nrf1** [comment]
That would the issue. I wanted visualize all of our samples. Since our sequences are much longer, and we have already done all the SNP calculations elsewhere, it is much better for us to upload an edge list with SNP distances rather than a sequence, especially as there are other variables we would like to include on the edges. But then we can’t filter out edges (see our other issue about that option disappearing, and even if the option didn’t disappear, we are off the scale), and we often will have samples that were included as controls or we thought were related but really should be unconnected based on SNP distance. So it would help us if there was a way to include a list of all nodes separate from the edge list, or if the edge list had a way to indicate an unconnected node (for example, if the target were empty).

**Comment by AABoyles** [comment]
I believe this issue has basically been resolved by 738c1dc520524f9c0c430fae7b1b29a086e219fd. It works in either (or both) of two ways:
1. You can specify reflexive links in the link CSV (i.e. set the `source` and `target` columns to the same value)
2. You can include a Node CSV with node `id`s which do not have any corresponding links in the Link CSV.
