### ISSUE TITLE
Unable to load  new file from other views

### ISSUE THREAD

**Issue by ikb6** [CDCgov/MicrobeTrace-Archive#130]
Perhaps it is designed that way, but if I go to a different view, say 3D network, and I close the original window by mistake, then I guess this 3D window does not function as the original one- it's only for viewing. I guess I was thrown off by New under the FILE dropdown menu

**Comment by AABoyles** [comment]
Oh, good one! I've removed the "New" button from all views except the Network (04708d9f1c5e8e4aabdb2e85136159c53ab923aa).
