### ISSUE TITLE
Confusing "Distance Matrix" Wiki Page

### ISSUE THREAD

**Issue by ikb6** [CDCgov/MicrobeTrace-Archive#139]
You have a section on distance matrix view in your help. This feature is not available in v 0.1.11. Any way to hide it or remove it until v 2.0 is released so as to not confuse users who may want to use the Github site for help?

**Comment by AABoyles** [comment]
Are you talking about the contents [this page](https://github.com/CDCgov/MicrobeTRACE/wiki/Distance-Matrix)? In the application it's called "[Heatmap](https://github.com/CDCgov/MicrobeTRACE/wiki/Heatmap)", and it is only available in MicrobeTrace Sessions based on FASTA files (we can't compute pairwise distance from edge lists).

**Comment by AABoyles** [comment]
Per e-mail conversation, I see this was in reference to the Distance-Matrix page of the Wiki. The offending page [has been deleted](https://github.com/CDCgov/MicrobeTRACE/wiki/_compare/691d862bae581933c147d740ba861f5eae0ad57a), and the [Heatmap](https://github.com/CDCgov/MicrobeTRACE/wiki/Heatmap) page [expanded](https://github.com/CDCgov/MicrobeTRACE/wiki/_compare/007676de5b077a1f9a56ff60d2182d3ab300322e) to cover the difference.

Thank you, @ikb6!
