### ISSUE TITLE
Table javascript error when highlighting nodes

### ISSUE THREAD

**Issue by ells** [CDCgov/MicrobeTrace-Archive#152]
Please take a look, relatively easy to replicate using the example files.

**Comment by AABoyles** [comment]
Yeah, the 0.1.x branch complains when you select a link (or a cluster?) from the table. Will patch

**Comment by AABoyles** [comment]
Resolved by 95cd5406e7bb3ebfb7ddf7d7e45e3eb2cdfd86a1
