### ISSUE TITLE
Network Find

### ISSUE THREAD

**Issue by nrf1** [CDCgov/MicrobeTrace-Archive#155]
In the network view, under the edit drop down, the first option is "Find", but nothing happens when you click on it.

**Comment by AABoyles** [comment]
Good bug find! There is a search interface, but it's hidden when you click on the "Find" button. Sorry about that!
For now, the workaround is to hit Ctrl-f, which reveals the search and places the focus on it (so you can just begin typing your search query, like you would in a browser or text editor).
This will be resolved in the transition from 0.1.11 to 0.2.0.
