### ISSUE TITLE
Radius size on map changes with zoom

### ISSUE THREAD

**Issue by nrf1** [CDCgov/MicrobeTrace-Archive#157]
If I zoom in on the map, then decide to change the radius size of the points, even the smallest setting results in very large points, and then after that if I move the map or change the zoom, the nodes change to tiny dots.
Setting node radius:
![image](https://user-images.githubusercontent.com/29959776/37470533-1c6fe6d8-283e-11e8-91a0-7e8a39a67a0b.png)

After moving the map:
![image](https://user-images.githubusercontent.com/29959776/37470544-215ddb0a-283e-11e8-94a9-f6b69987c6e3.png)

**Comment by AABoyles** [comment]
Thanks for reporting this. It will be resolved by the transition from 0.1.11 to 0.2.0.
