### ISSUE TITLE
Moving nodes

### ISSUE THREAD

**Issue by nrf1** [CDCgov/MicrobeTrace-Archive#158]
Sometimes a couple of nodes will not be in an ideal location, so it would be nice to be able to move the node and have it stay where you put it. Currently, when the user moves a node, it will often shift from the placed position. In other words, in would be nice to be able to manually rearrange nodes once the basic network has been drawn and have it stay in that layout (unless the user changes the network settings).

**Comment by AABoyles** [comment]
Good issue! Fortunately, MicrobeTrace actually has two ways to accomplish this:
1. Node Pinning - If you just want one node to stay where you put it, you can right-click on that node and click "Pin Node". If you then drag the node, it will stay where you drop it.
2. Infinite Friction - If you want all of the nodes to stay where you put them, go to the Settings' Network tab and drag the friction bar all the way to the right. Now none of the nodes will be able to move unless you drag them.

**Comment by AABoyles** [comment]
(Archival note: This is a duplicate of #30).
