### ISSUE TITLE
Selecting multiple nodes

### ISSUE THREAD

**Issue by nrf1** [CDCgov/MicrobeTrace-Archive#159]
In the manual, it says that the user can select multiple nodes with control-click, but this is not working for me; I only seem to be able to select one node at a time. Also, it would be nice to have a lasso feature, where you could select an entire cluster.

**Comment by AABoyles** [comment]
That's an error in the manual. You can multi-select nodes by holding _shift_ and clicking on the desired nodes in succession.
Visual Multiselect has been in the backlog for awhile (#3). Accordingly, I'm going to close this issue, but I'm working on it!
