### ISSUE TITLE
Many 0 distances

### ISSUE THREAD

**Issue by rlechtenberg** [CDCgov/MicrobeTrace-Archive#162]
I'm finding a suspiciously high frequency (>90%) of distances of 0.0 (this is using HIV sequences aligned to HXB2 by MicrobeTRACE), as reflected in the following histogram and heatmap:

![histogram](https://user-images.githubusercontent.com/38964413/39938597-500371da-5508-11e8-9dd7-1d127aed6702.png)
![heatmap](https://user-images.githubusercontent.com/38964413/39938885-45b2d56c-5509-11e8-94bf-7316212eb04e.png)

And in case it offers any clues as the where things are going awry, here is the alignment:
![alignment](https://user-images.githubusercontent.com/38964413/39938621-658d3022-5508-11e8-954c-1479be0f6592.JPG)

When I then tried aligned the sequences using mafft and running the alignment through ape::dist.dna(model = ‘TN93’) in R, I got approximately he same result (>90% genetic distances = 0.0). A colleague I consulted with inspected the alignment and noted "...there are quite a few ambiguous bases.  I believe dist.dna() skips sites with ambiguous bases as there’s no consensus on how to handle them amongst the various models it supports.  What you’re likely left with are sequences with very little distance after ambiguities are removed.  I suspect you’re running into the same limitation with whatever is calculating distances behind the scenes in the CDC tool." He noted that HIV-TRACE uses a method which takes into account ambiguities rather than skipping them, and that running my alignment through a tool he developed which does the same thing produced a reasonable-looking distance distribution. The network diagram produced is also consistent with the what the Secure HIV-TRACE manual describes as a consequence of clustering sequences with higher numbers of ambiguous bases:

![network](https://user-images.githubusercontent.com/38964413/39938753-d1b91932-5508-11e8-9851-60ba848a334e.JPG)

Does MicrobeTRACE resolve ambiguities, or is this potentially the underlying issue? And, related: does MicrobeTRACE screen for and eliminate laboratory contaminants the way Secure HIV-TRACE does?

Thanks a lot in advance for your help!

**Comment by AABoyles** [comment]
Great issue! Thanks for all the details, and especially for trying it in another environment.

To answer your question, MicrobeTrace uses the "average" resolution strategy by default, which is the same strategy that HIV-TRACE uses. That by itself should generate some non-zero distances, even in identical sequences, so long as those sequences contain some ambiguous codes.

...Actually, the weird thing isn't the spike near zero, but the long right-tail. TN93 is basically supposed to be bounded at 1 (and more practically bounded around .75 for two random sequences), but yours are going out to 3.5 for some reason. So whatever's going on under the hood, this is an honest-to-goodness bug.

Did you use MicrobeTrace's aligner to generate that alignment, or was it turned off? Also, what version of MicrobeTrace are you using?

**Comment by rlechtenberg** [comment]
Thanks Tony! Good to know how MicrobTRACE handles ambiguities.

Great point about the long right tail. I was so focused on the 0.0’s that I’d missed that. To answer your questions, (1) I did, indeed, use MicrobeTrace's aligner to generate that alignment (to HXB2) and (2) am using Version 0.1.12.

My present difficulties notwithstanding (we’ll see if those ultimately turn out to just be user error of some sort!), MicrobeTRACE is a really nice piece of software! I love how easy it is to explore the generated networks and all the ways one can do that, including even viewing the phylogenetic tree and sequence alignment.

**Comment by AABoyles** [comment]
Thanks a lot! It's been a lot of fun to develop.

Looking over your alignment, it looks like the MicrobeTrace aligner didn't do a very good job. If I were you, I'd try aligning it with a more flexible alignment tool like [MEGA](https://www.megasoftware.net/home), exporting the new alignment as a FASTA, loading that into MicrobeTrace, and turning OFF MicrobeTrace's aligner. It isn't the root of the bug, but it's a strong candidate for resolving the issue you're having. Either way, please let me know! If it helps, that will help me track down the bug. If it doesn't, that will also help me track down the bug, and I can keep trying to help!

**Comment by rlechtenberg** [comment]
Hi Tony, I tried your suggestion, aligning the sequences in MAFFT and feeding the resulting alignment (shown in first screenshot below) into MicrobeTRACE. The resulting network and histogram (also below) bear more of a resemblance to what I'd expect. 

I suppose I could always run my sequences through MAFFT before clustering in MicrobeTRACE but would be great if I could cut this step out of my workflow and just rely on MicrobeTRACE's alignment capabilities instead (esp. since the sequences in the MAFFT output are wrapped onto multiple lines and the extraneous line breaks need to be removed prior to inputting to MicrobeTRACE). Thanks for your continued assistance in troubleshooting!

![image](https://user-images.githubusercontent.com/38964413/40202633-794455c2-59d7-11e8-8346-a70b8cc300be.png)

![image](https://user-images.githubusercontent.com/38964413/40202504-0e4ac6b6-59d7-11e8-9969-38b385206478.png)

![image](https://user-images.githubusercontent.com/38964413/40202585-4d515f0a-59d7-11e8-902c-d313aa244633.png)

**Comment by AABoyles** [comment]
Hey @rlechtenberg, Thanks for trying the external aligner. Getting the aligner right in MicrobeTrace has been a loooong, uphill battle, and as you can see, we're not there yet. The next version of Microbetrace will have a much more configurable aligner with alignment previewing so you can judge the quality of the alignment before running the analysis. It isn't perfect out of the box, but it should help to get MAFFT out of the workflow.

**Comment by rlechtenberg** [comment]
Thanks for your continued development of MicrobeTRACE, @AABoyles! As an end user with limited bioinformatics training or experience, I wish I could say a preview of MicrobeTRACE's alignment would have led me to predict the problems I encountered but I can't; honestly, MicrobeTRACE's alignment looks as good to me as MAFFT's, although the results clearly argue otherwise! I've certainly gained an appreciation though for the importance of inspecting the distance histogram and taking networks with very high-degree nodes with a grain of salt! That's all to say that, to the extent that MicrobeTRACE's other end users may tend to also have limited bioinformatics expertise, it may be worth (to the extent possible) building in additional checks and/or means of automatically validating cluster analyses and flagging those that are suspect. Thanks again! Looking forward to the next version!
