### ISSUE TITLE
Feature requests

### ISSUE THREAD

**Issue by rlechtenberg** [CDCgov/MicrobeTrace-Archive#166]
Hi Tony,

I am using MicrobeTrace as part of a cluster response and it's been super helpful. I have a few suggestions coming out of my experience so far that I thought I might share:

- It would be great if settings were saved in a MicrobeTrace session. I'm finding that each time I re-open a previous saved session, I have to reset all the settings (i.e., aesthetic mappings for nodes and edges), which is quite cumbersome.
- It would be great if tooltips could contain the value of more than one variable or if they at least supported rich text so that, for example, a variable could be calculated (prior to import into MicrobeTrace) and used to create tooltips that show multiple key-value pairs on separate lines and formatted to improve readability, e.g.: 
     **variable1:** value
     **variable2:** value
     **variable3:** value
- It would be great if MicrobeTrace could show multiple links between a given node pair, (say a red one for a molecular link plus a blue one to indicate that one named the other through partner services, and maybe displaying these links as arcs to prevent overplotting).
- The ability to "Find" a node (say, based on it's ID or an attribute) could be useful when there are many in a network.
- It would be great if users could map other aesthetic attributes to variables such as edge line type, node outline color, and maybe node outline type as well.

Thanks a lot again for a great piece of software and a super useful tool! I'm excited for future versions of MicrobeTrace!

Regards,
Richard

**Comment by AABoyles** [comment]
Hey Richard!
Thanks for these feature requests. Before I get too far into them, development on MicrobeTrace has shifted from the installable program (this repository) to a [Web Application](https://microbetrace.herokuapp.com/). The new web application's issues section is [here](https://github.com/aaboyles/WebMicrobeTrace/issues). Now, on to your specific requests:

- Yes, maintaining settings in save files is [on the development radar](https://github.com/AABoyles/WebMicrobeTrace/issues/57).
- More complex tooltips are possible, but richtext probably won't be (trying to support it would open up a boatload of new security concerns). I'll discuss it with the team and see.
- Link origin-based striping was implemented in [Version 0.2.1](https://github.com/CDCgov/MicrobeTRACE/releases/tag/v0.2.1) and the [web version of MicrobeTrace](https://github.com/AABoyles/WebMicrobeTrace/commit/4d8f7c1c4660d83503248b4d016e923d1129d134).
- Searching has existed in MicrobeTrace for a long time. Try hitting Ctrl-f and typing something.
- I've resisted adding configurations like this in the past, but it may be time to re-think that. Again, Will consult with the team.

Thanks again Richard!
Tony

**Comment by rlechtenberg** [comment]
Thanks a lot in advance for considering the feature requests, Tony! FYI, Ctrl+F doesn't seem to work in the desktop version (I get a search box but then the relevant nodes aren't highlighted in any way upon entering search terms), but fine by me as I'll be using the web version from here on out anyway! Take care!
