### ISSUE TITLE
Accessible Color Palettes

### ISSUE THREAD

**Issue by AABoyles** [CDCgov/MicrobeTrace-Archive#61]
Presently, we provide a full rainbow palette, and shuffle through D3's default palette. I don't believe that this meets colorblind-accessible guidelines by default.

**Comment by rbenson** [comment]
Look at http://colorbrewer2.org/ for ideas about schemes

**Comment by AABoyles** [comment]
Resolved by 905753c1acaa625adcafb4e679bd71013265e892
