### ISSUE TITLE
Node shape mapping

### ISSUE THREAD

**Issue by AABoyles** [CDCgov/MicrobeTrace-Archive#7]

**Comment by billswitzer2** [comment]
Let's make this a priority too. Thx

**Comment by AABoyles** [comment]
+1 by @JJ67 (#38)

**Comment by AABoyles** [comment]
Resolved by 65e08367d439e21aa6b28dee56afe4625404dfe3
See also e562de5b95d6e11348b1dad5f722eea75eaf7647
