### ISSUE TITLE
Better Sample Files

### ISSUE THREAD

**Issue by AABoyles** [CDCgov/MicrobeTrace-Archive#92]
* Edge file with distances.
* FASTA file of HIV.
* FASTA file of something other than HIV.
* Node file with Lat/Lons.
* Node file with Zipcodes.
* Node file with Sequences.

**Comment by ells** [comment]
~~Edge file with distances.~~
~~FASTA file of HIV.~~
~~FASTA file of something other than HIV.~~
~~Node file with Lat/Lons.~~
~~Node file with Zipcodes.~~
~~Node file with Sequences.~~
